groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path("", views.ListGroups.as_view(), name="all"),
    path("new/", views.CreateGroup.as_view(), name="create"),
    path("posts/in/<slug>/", views.SingleGroup.as_view(), name="single"),
    path("join/<slug>/", views.JoinGroup.as_view(), name="join"),
    path("leave/<slug>/", views.LeaveGroup.as_view(), name="leave")
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path("", views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/", views.UserPosts.as_view(), name="for_user"),
    path("by/<username>/<int:pk>", views.PostDetail.as_view(), name="single"),
    path("delete/<int:pk>/", views.DeletePost.as_view(), name="delete")
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path("accounts/", include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("test/", views.TestPage.as_view(), name="test"),
    path("thanks/", views.ThanksPage.as_view(), name="thanks"),
    path("posts/", include('posts.urls', namespace='posts')),
    path("groups/", include('groups.urls', namespace='groups'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

groups/models.py
from django import template
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
# Create your models here.

import misaka

from django.contrib.auth import get_user_model

User = get_user_model()

register = template.Library()


class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(
        User, through='GroupMember', related_name='grp_members')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"slug": self.slug})

    class Meta:
        ordering = ['name']


class GroupMember(models.Model):
    group = models.ForeignKey(
        Group, related_name='memberships', on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, related_name='user_groups', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')

groups/views.py
from django.shortcuts import render
from django.contrib import messages
from . import models

# Create your views here.

from django.contrib.auth.mixins import (LoginRequiredMixin, PermissionRequiredMixin)

from django.urls import reverse
from django.views import generic
from django.shortcuts import get_object_or_404

from groups.models import Group, GroupMember

class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ('name', 'description')
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group

class JoinGroup(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user, group=group)
        except:
            messages.warning(self.request, 'Already a member!')
        else:
            messages.success(self.request, 'You are now a member!')

        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        try:
            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get('slug')
            ).get()

        except models.GroupMember.DoesNotExist:
            messages.warning(self.request, 'Sorry you are not the member of this group.')
        else:
            membership.delete()
            messages.success(self.request, 'You have left the group.')

        return super().get(request, *args, **kwargs)

groups/templates/groups/group_base.html
{% extends "base.html" %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'groups/css/groups_master.css' %}">
{% endblock styles %}

{% block content %}
<div class="container grp-container">
    <div class="row">
        {% block pregroup %}
        {% endblock %}
        {% block group_content %}
        {% endblock %}
        {% block postgroup %}
        {% endblock %}
    </div>
</div>
{% endblock %}

groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

{% block title_block %}
    {{group.name|capfirst}}
{% endblock %}

{% block pregroup %}
    <h1>{{group.name}}</h1>
    <h2>Member Count: {{group.members.count}}</h2>

    <div class="content">
        {% if user in group.members.all %}
            <a href="{% url 'groups:leave' slug=group.slug %}" class='btn btn--large btn-danger'>Leave</a>
        {% else %}
            <a href="{% url 'groups:join' slug=group.slug %}" class='btn btn--large btn-primary'>Join</a>

        {% endif %}
    </div>
{% endblock %}

{% block group_content %}
    <div class="col-md-8">
        {% if group.posts.count == 0 %}
            <h2>No posts.</h2>
        {% else %}
            {% for post in group.posts.all %}
                {% include 'posts/_post.html' %}
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}
{% load bootstrap4 %}

{% block title_block %}
    New Group
{% endblock %}

{% block group_content %}
    <h1>Create a new group!</h1>
    <form action="{% url 'groups:create' %}" method="POST" id='groupForm'>
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Create" class='btn btn-primary btn--large'>
    </form>
{% endblock %}

groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}
{% load static %}

{% block title_block %}
    Groups
{% endblock %}

{% block pregroup %}
    <div class="col-md-4">
        <div class="content">
            {% if user.is_authenticated %}
                <h2>Welcome back!
                    <a href="{% url 'posts:for_user' username=user.username %}">@{{user.username}}</a>
                </h2>
            {% endif %}
            <h2>Groups</h2>
            <h4>Welcome to the groups page!</h4>
        </div>
        {% if user.is_authenticated %}
            <a href="{% url 'groups:create' %}" class='btn btn-dark'>Create Group</a>
        {% endif %}
    </div>
{% endblock %}

{% block group_content %}
    <div class="col-md-8">
        <div class="list-group">
            {% for group in object_list %}
                <a href="{% url 'groups:single' slug=group.slug %}" class='list-group-item'>
                    <h3>{{group.name}}</h3>
                    <div class="container-fluid">
                        {{group.description_html|safe}}
                        <div class="row">
                            <div class="col-md-4">
                                <span class='badge bg-secondary'>{{group.members.count}}</span>
                                Members
                            </div>
                            <div class="col-md-4">
                                <span class='badge bg-secondary'>{{group.posts.count}}</span>
                                Posts
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}