accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name='accounts/login.html'), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUp.as_view(), name="signup")
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path("", views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/", views.UserPosts.as_view(), name="for_user"),
    path("by/<username>/<int:pk>", views.PostDetail.as_view(), name="single"),
    path("delete/<int:pk>/", views.DeletePost.as_view(), name="delete")
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path("accounts/", include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("test/", views.TestPage.as_view(), name="test"),
    path("thanks/", views.ThanksPage.as_view(), name="thanks"),
    path("posts/", include('posts.urls', namespace='posts')),
    path("groups/", include('groups.urls', namespace='groups'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title_block %}{% endblock %}</title>
        <meta name="description" content="This is the star social.">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        {% comment %} <-- custom libraries --> {% endcomment %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

        <link rel="stylesheet" href="{% static 'css/master.css' %}">

        {% block styles %}
        {% endblock styles %}
    </head>
    <body>

        <nav class='navbar navbar-expand-lg navbar-dark bg-dark mynav' role='navigation' id='navbar'>
            <div class="container">
                <a class='navbar-brand mynav' href="{% url 'home' %}">Star Social</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse text-right" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        {% if user.is_authenticated %}
                            <li class='nav-item'><a class="nav-link" href="{% url 'posts:create' %}">Post</a></li>
                            <li class='nav-item'><a class="nav-link" href="{% url 'groups:all' %}">Groups</a></li>
                            <li class='nav-item'><a class="nav-link" href="{% url 'groups:create' %}">Create Group</a></li>
                            <li class='nav-item'><a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a></li>
                        {% else %}
                            <li class='nav-item'><a class="nav-link" href="{% url 'groups:all' %}">Groups</a></li>
                            <li class='nav-item'><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
                            <li class='nav-item'><a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <div id="particles-js"></div>
        {% block content %}
        {% endblock %}
        {% comment %} <div id="particles-js"></div> {% endcomment %}
    </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title_block %}
    Index
{% endblock %}

{% block content %}
    <h1>Welcome to Star Social!</h1>
    {% comment %} <div class="aopd-api-data">
        <h3>    
            {{aopd_data.copyright}}
        </h3>
        <p>{{aopd_data.explanation}}</p>
        <img id="api-image" src="{{aopd_data.url}}" alt="Error 404" title="{{aopd_data.title}}">
    </div> {% endcomment %}
    <div class="container index-container">
        <div class="left">
            <figure>
                <figcaption>NASA Astronomy Photo of the Day</figcaption>
                <img id="apod-img" src="{{aopd_data.url}}" title={{aopd_data.title}} alt="">
            </figure>
            <div class="featured-news">
                <h2><a href="{{featured_data.url}}">{{featured_data.name}}</a></h2>
                <img id="featured-image" src="{{featured_data.thumbnail_retina}}" alt="">
                <p id="featured-text">{{featured_data.abstract}}</p>
            </div>
        </div>
        <div class="right">
            <div class="news card text-center">
                <div class="card-body">
                    <h4 class="card-title">Your News</h4>
                    <div class="card-text">
                        <ul class="list-group list-group-flush">
                            {% for news in news_data|slice:":5" %}
                                <li class="list-group-item"><a href="{{news.url}}">{{news.name}}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="mars-api-data">
                <table>
                    <caption>Mars Temprature Data</caption>
                    <tr>
                        <th>Average Temperature °C</th>
                        <th>Current Season</th>
                    </tr>

                    {% for key, value in mars_data.items %}
                    <tr>
                        {% if key in mars_data.sol_keys %}
                            <td>{{value.AT.av|default:"Not Available"}}</td>
                            <td>{{value.Season}}</td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
    <script src="{% static 'js/master.js' %}" async defer></script>
{% endblock %}

templates/test.html
{% extends 'base.html' %}
{% load static %}

{% block title_block %}
    Login
{% endblock title_block %}


{% block styles %}
    <link rel="stylesheet" href="{% static 'css/test.css' %}">
{% endblock styles %}

{% block content %}
    <h1>You are now logged in.</h1>
{% endblock content %}

templates/thanks.html
{% extends 'base.html' %}
{% block content %}
    <h1>Thanks for visiting!</h1>
{% endblock %}