posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path("", views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/", views.UserPosts.as_view(), name="for_user"),
    path("by/<username>/<int:pk>", views.PostDetail.as_view(), name="single"),
    path("delete/<int:pk>/", views.DeletePost.as_view(), name="delete")
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path("accounts/", include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("test/", views.TestPage.as_view(), name="test"),
    path("thanks/", views.ThanksPage.as_view(), name="thanks"),
    path("posts/", include('posts.urls', namespace='posts')),
    path("groups/", include('groups.urls', namespace='groups'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

import misaka

from groups.models import Group
# Create your models here.

from django.contrib.auth import get_user_model

User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name='posts', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("posts:single", kwargs={"pk": self.pk,
        'username':self.user.username})

    class Meta:
        ordering = ['-created_at']
        unique_together = ['user', 'message']
    

posts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from django.http import Http404
from django.views import generic
from django.contrib import messages


from braces.views import SelectRelatedMixin

from groups.models import Group
from . import models
from . import forms

from django.contrib.auth import get_user_model

# Create your views here.

User = get_user_model()


class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ('user', 'group')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            self.user_grp = User.objects.get(
                username__iexact=self.request.user)
        except:
            context["other_groups"] = Group.objects.all()
        else:
            context["user_groups"] = self.user_grp.grp_members.all()
        return context


class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(
                username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context


class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ('message', 'group')
    model = models.Post

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post Deleted')
        return super().delete(*args, **kwargs)

posts/templates/posts/_post.html
<div class="post media">
    <h3 id="post-title"><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{post.message_html|safe}}</a></h3>
    <div class="media-body">
        {% comment %} <strong>{{post.user.username}}</strong> {% endcomment %}
        <h5>
            <span>
                <a href="{% url 'posts:for_user' username=post.user.username %}">@{{post.user.username}}</a>
            </span>
            <time>
                {{post.created_at}}
            </time>
        </h5>

        <div class="media-footer">
            {% if user.is_authenticated and post.user == user and not hide_delete %}
                <a href="{% url 'posts:delete' pk=post.pk %}" title='delete' class='btn btn-danger post-btn'>Delete</a>
            {% endif %}
        
        </div>
    </div>
</div>

posts/templates/posts/post_base.html
{% extends "base.html" %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'posts/css/posts_master.css' %}">
{% endblock styles %}

{% block content %}
<div class="posts-page">
    <div class="container posts-container">
        <div class="row">
            {% block prepost %}
            {% endblock %}
            {% block post_content %}
            {% endblock %}
            {% block post_post %}
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}

{% block title_block %}
    Confirm Delete
{% endblock %}

{% block post_content %}
    <h3>Are you sure you want to delete this post?</h3>
    <div class="posts">
        {% include 'posts/_post.html' with post=object hide_delete=True %}
    </div>
    <form method='POST'>
        {% csrf_token %}
        <input type="submit" value="Confirm Delete" class='btn btn-danger'>
        <a href="{% url 'posts:single' username=user.username pk=object.pk %}" class='btn btn-outline-warning'>Cancel</a>
    </form>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'posts/post_base.html' %}
{% load static %}

{% block title_block %}
    Post
{% endblock %}

{% block post_content %}
    <div class="col-md-8">
        {% include 'posts/_post.html' %}
    </div>
{% endblock %}

posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
{% load bootstrap4 %}

{% block title_block %}
    New Post
{% endblock %}

{% block post_content %}
    <h1>Create a new post!</h1>
        <form action="{% url 'posts:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" value="Post" class='btn btn-primary btn-large'>
        </form>
{% endblock %}

posts/templates/posts/post_list.html
{% extends 'posts/post_base.html' %}

{% block title_block %}
    Posts
{% endblock %}

{% block prepost %}
    <div class="col-md-4">
        {% if user.is_authenticated %}
            <div class="card text-center">
                <div class="card-body">
                    <h4 class="card-title">Your Groups</h4>
                    <div class="card-text">
                        <ul class="list-group list-group-flush">
                            {% for member_group in user_groups %}
                                <li class="list-group-item"><a href="{% url 'groups:single' slug=member_group.slug %}">{{member_group}}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="card text-center">
                <div class="card-body">
                    <h4 class="card-title">All Groups</h4>
                    <div class="card-text">
                        <ul class="list-group list-group-flush">
                            {% for other_group in other_groups %}
                                <li class="list-group-item"><a href="{% url 'groups:single' slug=other_group.slug %}">{{other_group}}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block post_content %}
    <div class="col-md-8">
        {% for post in post_list %}
            {% include 'posts/_post.html' %}
        {% endfor %}
    </div>

{% endblock %}

posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block title_block %}
    Profile
{% endblock %}

{% block prepost %}
    <div class="col-md-4">
        <h1>@{{post_user.username}}</h1>
    </div>
{% endblock %}

{% block post_content %}
    <div class="col-md-8">
        {% for post in post_list %}
            {% include "posts/_post.html" %}
        {% endfor %}
    </div>
{% endblock post_content %}